version: '3'
services:
  my-timesheet:
    container_name: my-timesheet
    image: timesheet:1
    restart: always
    environment:
      GOOGLE_OAUTH_CLIENT_ID: 692575898397-dnt9sqi2jstddfepsng04p9ac4oj7p4n.apps.googleusercontent.com
      GOOGLE_OAUTH_CLIENT_SECRET: Bt67Uhhu9SVqvxR3uFRc6IjL
    build:
      context: .
    depends_on:
      - my-mariadb
    ports:
    - 8080:8080

  my-mariadb:
    container_name: my-mariadb
    image: mariadb:10.4.8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timesheet
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
    - 3306:3306
    